### ISSUE TITLE
Plugin INGInious-problems-math not installing

### ISSUE THREAD

**Issue by dodo-a11y** [UCL-INGI/INGInious-problems-math#18]
Hi, Please help me install the plugin, I have "Hintpage" and "FontBootstrap" import errors

**Comment by Drumor** [comment]
Hello,

Could you first explain what you already did to install the plugin?

Also, could you paste the stacktrace?

**Comment by dodo-a11y** [comment]
hi, I installed the INGINIOUS-problem-math plugin via pip3, I also added it
in the config.yaml file.  But according to the errors in the logs it
requires the installation of Flask what I have already done then I will now
give you errors related to the import of "hintPage" and "Font_bootstrap"

Le jeu. 27 mai 2021 à 07:13, Ludovic Taffin ***@***.***> a
écrit :

**Comment by Drumor** [comment]
Could you give the stacktrace please?

**Comment by dodo-a11y** [comment]
I will send you the slake trace shortly, as I am on an internship I am freeing myself to go work on INGInious

**Comment by dodo-a11y** [comment]
I use version 6 of INGInious, I also take this opportunity to ask you if possible to update to version 7

**Comment by anthonygego** [comment]
Did you try to install the master branch ? You can use `ìnginious-database-update`` once deployed with pip to convert your existing data. Once installed, all the available plugins should work.

**Comment by dodo-a11y** [comment]
please tell me how to use "nginious-database-update" for deployment

**Comment by anthonygego** [comment]
You just need to run the tool once you installed the new version with pip, by specifying the config file: https://docs.inginious.org/en/latest/commands_doc/inginious-database-update.html

**Comment by dodo-a11y** [comment]
[Tue Jun 01 11:16:45.245643 2021] [wsgi:error] [pid 4286:tid 140449305679616] [client 192.168.100.13:4690]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load, referer: http://192.168.100.2/courselist
[Tue Jun 01 11:16:45.245651 2021] [wsgi:error] [pid 4286:tid 140449305679616] [client 192.168.100.13:4690]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked, referer: http://192.168.100.2/courselist
[Tue Jun 01 11:16:45.245659 2021] [wsgi:error] [pid 4286:tid 140449305679616] [client 192.168.100.13:4690]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked, referer: http://192.168.100.2/courselist
[Tue Jun 01 11:16:45.245666 2021] [wsgi:error] [pid 4286:tid 140449305679616] [client 192.168.100.13:4690]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module, referer: http://192.168.100.2/courselist
[Tue Jun 01 11:16:45.245674 2021] [wsgi:error] [pid 4286:tid 140449305679616] [client 192.168.100.13:4690]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed, referer: http://192.168.100.2/courselist
[Tue Jun 01 11:16:45.245682 2021] [wsgi:error] [pid 4286:tid 140449305679616] [client 192.168.100.13:4690]   File "/usr/local/lib/python3.6/dist-packages/inginious_problems_math/__init__.py", line 11, in <module>, referer: http://192.168.100.2/courselist
[Tue Jun 01 11:16:45.245686 2021] [wsgi:error] [pid 4286:tid 140449305679616] [client 192.168.100.13:4690]     from inginious_problems_math.pages.hint import HintPage, referer: http://192.168.100.2/courselist
[Tue Jun 01 11:16:45.245693 2021] [wsgi:error] [pid 4286:tid 140449305679616] [client 192.168.100.13:4690]   File "/usr/local/lib/python3.6/dist-packages/inginious_problems_math/pages/hint.py", line 11, in <module>, referer: http://192.168.100.2/courselist
[Tue Jun 01 11:16:45.245697 2021] [wsgi:error] [pid 4286:tid 140449305679616] [client 192.168.100.13:4690]     from inginious.frontend.pages.course import handle_course_unavailable, referer: http://192.168.100.2/courselist
[Tue Jun 01 11:16:45.245712 2021] [wsgi:error] [pid 4286:tid 140449305679616] [client 192.168.100.13:4690] ImportError: cannot import name 'handle_course_unavailable', referer: http://192.168.100.2/courselist

**Comment by dodo-a11y** [comment]
Here are the errors I find when trying to install the plugin

**Comment by anthonygego** [comment]
There are many chances you're still on the v0.6 branch, as ``handle_course_unavailable`` has been defined a bit later. You can check this by running ``pip show inginious``. The latest code will show ``0.7dev...``. Make sure that you add the ``--upgrade`` argument using pip.

**Comment by dodo-a11y** [comment]
dodo @ INGI-PC: ~ $ pip show inginious
dodo @ INGI-PC: ~ $


Excuse me please but the pip show inginious command shows me nothing.
I might be really on the v06 branch. If you mind, give me the full code for the pip --upgrade

**Comment by dodo-a11y** [comment]
dodo @ INGI-PC: ~ $ pip show inginious
dodo @ INGI-PC: ~ $


Excuse me please but the pip show inginious command shows me nothing.
I might be really on the v06 branch. If you mind, give me the full code for the pip --upgrade

**Comment by dodo-a11y** [comment]
dodo @ INGI-PC: ~ $ pip3 show inginious
Nom: INGInious
Version: 0.6.dev0
Résumé: Une niveleuse intelligente qui permet de tester de manière sécurisée et automatisée le code créé par les étudiants.
Page d'accueil: https://github.com/UCL-INGI/INGInious
Auteur: contributeurs INGInious
E-mail de l'auteur: inginious@info.ucl.ac.be
Licence: AGPL 3
Emplacement: /usr/local/lib/python3.6/dist-packages
Nécessite: PyYAML, WsgiDAV, docker, docutils, httplib2, lti, msgpack, natsort, oauth2, psutil, pymongo, pytidylib, pyzmq, sh, watchdog, web.py, zipstream

c'est bon maintenant je suis toujours sur la branche v06

**Comment by anthonygego** [comment]
You can update your install by running ``pip install --upgrade git+https://github.com/UCL-INGI/INGInious``.

**Comment by dodo-a11y** [comment]
[Tue Jun 01 12:33:43.027792 2021] [wsgi:error] [pid 4474:tid 140132745201408] [client 192.168.100.13:5265]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load, referer: http://192.168.100.2/mycourses
[Tue Jun 01 12:33:43.027809 2021] [wsgi:error] [pid 4474:tid 140132745201408] [client 192.168.100.13:5265]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked, referer: http://192.168.100.2/mycourses
[Tue Jun 01 12:33:43.027825 2021] [wsgi:error] [pid 4474:tid 140132745201408] [client 192.168.100.13:5265]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked, referer: http://192.168.100.2/mycourses
[Tue Jun 01 12:33:43.027842 2021] [wsgi:error] [pid 4474:tid 140132745201408] [client 192.168.100.13:5265]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module, referer: http://192.168.100.2/mycourses
[Tue Jun 01 12:33:43.027858 2021] [wsgi:error] [pid 4474:tid 140132745201408] [client 192.168.100.13:5265]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed, referer: http://192.168.100.2/mycourses
[Tue Jun 01 12:33:43.027875 2021] [wsgi:error] [pid 4474:tid 140132745201408] [client 192.168.100.13:5265]   File "/usr/local/lib/python3.6/dist-packages/inginious_problems_math/__init__.py", line 11, in <module>, referer: http://192.168.100.2/mycourses
[Tue Jun 01 12:33:43.027885 2021] [wsgi:error] [pid 4474:tid 140132745201408] [client 192.168.100.13:5265]     from inginious_problems_math.pages.hint import HintPage, referer: http://192.168.100.2/mycourses
[Tue Jun 01 12:33:43.027911 2021] [wsgi:error] [pid 4474:tid 140132745201408] [client 192.168.100.13:5265]   File "/usr/local/lib/python3.6/dist-packages/inginious_problems_math/pages/hint.py", line 11, in <module>, referer: http://192.168.100.2/mycourses
[Tue Jun 01 12:33:43.027921 2021] [wsgi:error] [pid 4474:tid 140132745201408] [client 192.168.100.13:5265]     from inginious.frontend.pages.course import handle_course_unavailable, referer: http://192.168.100.2/mycourses
[Tue Jun 01 12:33:43.027951 2021] [wsgi:error] [pid 4474:tid 140132745201408] [client 192.168.100.13:5265] ImportError: cannot import name 'handle_course_unavailable', referer: http://192.168.100.2/mycourses

**Comment by dodo-a11y** [comment]
The update worked but this time here are the above log errors.

**Comment by anthonygego** [comment]
You may want to check that your file ``/usr/local/lib/python3.6/dist-packages/inginious/frontend/pages/course.py`` actually contains the ``handle_course_unavailable`` function as it is defined here : https://github.com/UCL-INGI/INGInious/blob/master/inginious/frontend/pages/course.py#L14

**Comment by dodo-a11y** [comment]
# -*- coding: utf-8 -*-
#
# This file is part of INGInious. See the LICENSE and the COPYRIGHTS files for
# more information about the licensing of this file.

""" Course page """
import web

from inginious.frontend.pages.utils import INGIniousAuthPage, INGIniousPage


class CoursePage(INGIniousPage):
    """ Course page """

    def get_course(self, courseid):
        """ Return the course """
        try:
            course = self.course_factory.get_course(courseid)
        except:
            raise web.notfound()

        return course

    def POST(self, courseid):  # pylint: disable=arguments-differ
        """ POST request """
        course = self.get_course(courseid)

        user_input = web.input()
        if "unregister" in user_input and course.allow_unregister():
            self.user_manager.course_unregister_user(course, self.user_manager.session_username())
            raise web.seeother(self.app.get_homepath() + '/mycourses')

        return self.show_page(course)

    def GET(self, courseid):  # pylint: disable=arguments-differ
        """ GET request """
        course = self.get_course(courseid)
        return self.show_page(course)

    def show_page(self, course):
        """ Prepares and shows the course page """
        username = self.user_manager.session_username()
        if not self.user_manager.course_is_open_to_user(course, lti=False):
            return self.template_helper.get_renderer().course_unavailable()
        else:
            tasks = course.get_tasks()
            last_submissions = self.submission_manager.get_user_last_submissions(5, {"courseid": course.get_id(), "taskid": {"$in": list(tasks.keys())}})

            for submission in last_submissions:
                    submission["taskname"] = tasks[submission['taskid']].get_name(self.user_manager.session_language())

            tasks_data = {}
            user_tasks = self.database.user_tasks.find({"username": username, "courseid": course.get_id(), "taskid": {"$in": list(tasks.keys())}})
            is_admin = self.user_manager.has_staff_rights_on_course(course, username)

            tasks_score = [0.0, 0.0]

            for taskid, task in tasks.items():
                tasks_data[taskid] = {"visible": task.get_accessible_time().after_start() or is_admin, "succeeded": False,
                                      "grade": 0.0}
                tasks_score[1] += task.get_grading_weight() if tasks_data[taskid]["visible"] else 0

            for user_task in user_tasks:
                tasks_data[user_task["taskid"]]["succeeded"] = user_task["succeeded"]
                tasks_data[user_task["taskid"]]["grade"] = user_task["grade"]

                weighted_score = user_task["grade"]*tasks[user_task["taskid"]].get_grading_weight()
                tasks_score[0] += weighted_score if tasks_data[user_task["taskid"]]["visible"] else 0

            course_grade = round(tasks_score[0]/tasks_score[1]) if tasks_score[1] > 0 else 0
            tag_list = course.get_tags()
            user_info = self.database.users.find_one({"username": username})

            return self.template_helper.get_renderer().course(user_info, course, last_submissions, tasks, tasks_data, course_grade, tag_list)

**Comment by dodo-a11y** [comment]
here is my course.py file, the handle_course_unavailable function is missing

**Comment by Drumor** [comment]
As @anthonygego  previously said, u probably not use last version so...
Please try a pip install --upgrade

**Comment by anthonygego** [comment]
I'm closing this as this thread has been inactive since more than a year. Feel free to reopen it if your issue is still present.
