### ISSUE TITLE
'NoneType' error when submitting with the plugin

### ISSUE THREAD

**Issue by Manon-Oreins** [UCL-INGI/INGInious-problems-math#24]
When installing INGInious with the plugin math on Ubuntu 20.04  and having antlr4-python3-runtime 4.10 and python 3.8.10 we get a 'NoneType' error when submitting an answer in a task using the plugin.

Seems to be fixed on the version 4.10.1 of antlr4 but not release yet for pip : https://github.com/antlr/antlr4/issues/3753

FIX : use version 4.9.3 of antlr4 and python 3.8.10

**Comment by anthonygego** [comment]
Mitigated by 82ac7b86ba096aec19cf1933d9d1271b3238e1ac
