### ISSUE TITLE
Error message is not related to the error

### ISSUE THREAD

**Issue by Drumor** [UCL-INGI/INGInious-problems-math#4]
Related to #3
For no specific reason, the feedback given is not related to the wrong answer.
For example in the example given, the feedback given is "Not correct :  2 e^{x^2-4y^2}xz^2" which is not exactly what the student answered. (e.g : e^{x^2-4y^2}2xz^2)

**Comment by darkyne** [comment]
The parser to convert the student input into a sympy expression sometimes reorganizes the terms order while not modifying the mathematical meaning.
This also means the feedback saying an answer is wrong may show a slightly different version compared to the exact string that was given as input. For example if the student enters 5² which was a wrong answer, the feedback may say "Not correct: 25".
I am not sure it should really be considered as an issue but here is the explanation why it happens.
